import * as fs from 'fs';
import * as path from 'path';
import express from 'express';
import { createExedra } from '../src';
import { getMetadata, RouteMetadata } from '../src/metadata';
import { getParamBindings, ParamBinding } from '../src/attributes/param';
import { Group } from '../src/routing/group';
import { Route } from '../src/routing/route';
import RootController from './controllers/RootController';

const OUTPUT_FILE = path.join(__dirname, 'README.md');

// ─── Runtime introspection ───────────────────────────────────────────────────

interface ControllerInfo {
  className: string;
  filePath: string;
  classMeta: RouteMetadata;
  methods: MethodInfo[];
  middlewareNames: string[];
  childControllers: string[];
}

interface MethodInfo {
  name: string;
  httpVerb: string | null;
  routePath: string | null;
  fullName: string;
  methodMeta: RouteMetadata;
  paramBindings: Record<number, ParamBinding>;
}

function collectControllerInfo(group: Group): Map<string, ControllerInfo> {
  const map = new Map<string, ControllerInfo>();

  function walk(g: Group): void {
    for (const route of g.routes) {
      const controllerClass = route.properties.controllerClass;
      if (!controllerClass) continue;

      const className = controllerClass.name;
      if (!map.has(className)) {
        const classMeta = getMetadata(controllerClass);

        // Detect middleware* prefix methods from the prototype
        const middlewareNames: string[] = [];
        const proto = controllerClass.prototype;
        for (const methodName of Object.getOwnPropertyNames(proto)) {
          if (methodName === 'constructor') continue;
          if (methodName.startsWith('middleware')) {
            middlewareNames.push(methodName);
          }
        }

        // Also include @Middleware decorator entries
        if (classMeta.middleware) {
          for (const entry of classMeta.middleware) {
            const name = typeof entry === 'function' ? entry.name || 'anonymous' : String(entry);
            if (!middlewareNames.includes(name)) {
              middlewareNames.push(name);
            }
          }
        }

        map.set(className, {
          className,
          filePath: route.properties.controllerPath || className,
          classMeta,
          methods: [],
          middlewareNames,
          childControllers: [],
        });
      }

      const info = map.get(className)!;
      const action = route.properties.action;

      // Collect child controllers (subrouting)
      const childGroup: Group | undefined = route.properties._childGroup;
      if (childGroup) {
        for (const childRoute of childGroup.routes) {
          const childClass = childRoute.properties.controllerClass;
          if (childClass && !info.childControllers.includes(childClass.name)) {
            info.childControllers.push(childClass.name);
          }
        }
        walk(childGroup);
      }

      // Collect method info for route-bearing methods
      if (route.method && action) {
        const methodMeta = getMetadata(controllerClass, action);
        const paramBindings = getParamBindings(controllerClass.prototype, action);

        info.methods.push({
          name: action,
          httpVerb: route.method,
          routePath: route.path || null,
          fullName: route.fullName,
          methodMeta,
          paramBindings,
        });
      }
    }
  }

  walk(group);
  return map;
}

// ─── Markdown generation ─────────────────────────────────────────────────────

function generateMarkdown(
  routes: ReturnType<Group['listRoutes']>,
  controllers: Map<string, ControllerInfo>,
): string {
  const lines: string[] = [];

  lines.push('# Examples — Routing Structure');
  lines.push('');
  lines.push('Auto-generated by `npm run examples:document-structure`.');
  lines.push('');

  // Quick start
  lines.push('## Quick Start');
  lines.push('');
  lines.push('```bash');
  lines.push('npm run dev              # Start the example app on http://localhost:3545');
  lines.push('npm run example:routes   # List all registered routes');
  lines.push('```');
  lines.push('');

  // Bootstrap
  lines.push('## Bootstrap');
  lines.push('');
  lines.push('`examples/app.ts` configures Express and wires up exedra:');
  lines.push('');
  lines.push('```typescript');
  lines.push('const rootGroup = createExedra(app, {');
  lines.push('  controller: RootController,');
  lines.push('  namedParamAutoInject: true,  // parameter names resolve automatically');
  lines.push('  useFlatRouting: true          // all routes on parent router (no sub-routers)');
  lines.push('});');
  lines.push('```');
  lines.push('');
  lines.push(
    'Global middleware: request logging, CORS headers, `express.json()`, `express.urlencoded()`.',
  );
  lines.push('');

  // Subrouting hierarchy — built from controller metadata
  lines.push('## Subrouting Hierarchy');
  lines.push('');
  lines.push('```');
  buildHierarchyTree(lines, controllers);
  lines.push('```');
  lines.push('');

  // Route table — from listRoutes()
  lines.push('## Route Table');
  lines.push('');
  lines.push('| Method | Path | Controller | Action | Name |');
  lines.push('|--------|------|------------|--------|------|');

  for (const r of routes) {
    lines.push(`| ${r.method} | ${r.fullPath} | ${r.controller} | ${r.action}() | ${r.fullName} |`);
  }
  lines.push('');

  // Controller reference — from Reflect metadata
  lines.push('## Controller Reference');
  lines.push('');

  const sorted = [...controllers.values()].sort((a, b) => {
    if (a.className === 'RootController') return -1;
    if (b.className === 'RootController') return 1;
    return a.className.localeCompare(b.className);
  });

  for (const ctrl of sorted) {
    if (ctrl.className === 'RootController' || ctrl.className === 'WebController') continue;

    lines.push(`### ${ctrl.className}`);
    lines.push('');
    lines.push(`- **File:** \`${ctrl.filePath}\``);
    if (ctrl.classMeta.path) lines.push(`- **Base path:** \`${ctrl.classMeta.path}\``);
    if (ctrl.classMeta.tag) lines.push(`- **Tag:** \`${ctrl.classMeta.tag}\``);
    if (ctrl.classMeta.name) lines.push(`- **Name:** \`${ctrl.classMeta.name}\``);

    // Class-level states (includes @Validation, @Transformer, @State)
    if (ctrl.classMeta.states && Object.keys(ctrl.classMeta.states).length > 0) {
      const stateEntries = Object.entries(ctrl.classMeta.states)
        .filter(([k]) => !k.startsWith('exedra:'))
        .map(([k, v]) => `\`${k}=${JSON.stringify(v)}\``);
      if (stateEntries.length > 0) {
        lines.push(`- **Class state:** ${stateEntries.join(', ')}`);
      }
    }

    // Class-level flags
    if (ctrl.classMeta.flags && ctrl.classMeta.flags.length > 0) {
      lines.push(`- **Class flags:** ${ctrl.classMeta.flags.map((f) => `\`${f}\``).join(', ')}`);
    }

    // Middleware
    if (ctrl.middlewareNames.length > 0) {
      lines.push(`- **Middleware:** ${ctrl.middlewareNames.map((m) => `\`${m}\``).join(', ')}`);
    }

    // Subrouting
    if (ctrl.childControllers.length > 0) {
      lines.push(`- **Subrouting:** ${ctrl.childControllers.map((c) => `\`${c}\``).join(', ')}`);
    }

    // Methods
    if (ctrl.methods.length > 0) {
      lines.push(`- **Routes:**`);
      for (const m of ctrl.methods) {
        const extras: string[] = [];

        // Method-level states
        if (m.methodMeta.states) {
          for (const [key, val] of Object.entries(m.methodMeta.states)) {
            if (key === 'exedra:validation') {
              extras.push(`@Validation(${JSON.stringify(val)})`);
            } else if (key === 'exedra:transformer') {
              extras.push(`@Transformer(${(val as any)?.name || val})`);
            } else {
              extras.push(`@State(${key}=${JSON.stringify(val)})`);
            }
          }
        }

        // Method-level flags
        if (m.methodMeta.flags && m.methodMeta.flags.length > 0) {
          extras.push(`@Flag(${m.methodMeta.flags.join(', ')})`);
        }

        // Method-level serieses
        if (m.methodMeta.serieses) {
          for (const [key, val] of Object.entries(m.methodMeta.serieses)) {
            extras.push(`@Series(${key}=${JSON.stringify(val)})`);
          }
        }

        // Parameter decorators
        for (const binding of Object.values(m.paramBindings)) {
          extras.push(formatParamBinding(binding));
        }

        // FailRoute
        if (m.methodMeta.asFailRoute) {
          extras.push('@FailRoute');
        }

        const extraStr = extras.length > 0 ? ` — ${extras.join(', ')}` : '';
        const methodPath = m.routePath || '';
        lines.push(`  - \`${m.httpVerb} ${methodPath}\` \`${m.name}()\`${extraStr}`);
      }
    }
    lines.push('');
  }

  // Decorator index — aggregated from all controllers
  lines.push('## Decorator Index');
  lines.push('');
  lines.push('| Decorator | Demonstrated In | Purpose |');
  lines.push('|-----------|----------------|---------|');
  buildDecoratorIndex(lines, controllers);
  lines.push('');

  return lines.join('\n');
}

function formatParamBinding(binding: ParamBinding): string {
  let keyStr = '()';
  if (binding.key !== undefined && binding.key !== null) {
    // For class constructors (from @Inject), use the class name
    const keyName = typeof binding.key === 'function' ? binding.key.name : String(binding.key);
    keyStr = `('${keyName}')`;
  }
  const typeName = binding.type.charAt(0).toUpperCase() + binding.type.slice(1);
  return `@${typeName}${keyStr}`;
}

function buildHierarchyTree(lines: string[], controllers: Map<string, ControllerInfo>): void {
  const root = controllers.get('RootController');
  if (!root) return;

  lines.push('RootController (/)');

  const rootChildren = findChildControllers(root, controllers);
  for (let i = 0; i < rootChildren.length; i++) {
    const child = rootChildren[i];
    const isLast = i === rootChildren.length - 1;
    renderSubtree(lines, child.name, controllers, '', isLast);
  }
}

function renderSubtree(
  lines: string[],
  controllerName: string,
  controllers: Map<string, ControllerInfo>,
  parentIndent: string,
  isLast: boolean,
): void {
  const info = controllers.get(controllerName);
  if (!info) return;

  const connector = isLast ? '└──' : '├──';
  const indent = parentIndent + (isLast ? '    ' : '│   ');

  const pathStr = info.classMeta.path || '/';
  lines.push(`${parentIndent}${connector} ${controllerName} (${pathStr})`);

  // Show routes
  if (info.methods.length > 0) {
    const children = findChildControllers(info, controllers);
    const totalItems = info.methods.length + children.length;
    let itemIdx = 0;

    const maxVerbLen = Math.max(...info.methods.map((m) => (m.httpVerb ?? '').length));
    const maxPathLen = Math.max(...info.methods.map((m) => (m.routePath || '/').length));

    for (const m of info.methods) {
      itemIdx++;
      const isLastItem = itemIdx >= totalItems;
      const routeConnector = isLastItem ? '└──' : '├──';
      const methodPath = m.routePath || '/';
      const verb = (m.httpVerb ?? '').padEnd(maxVerbLen);
      const paddedPath = methodPath.padEnd(maxPathLen);
      lines.push(`${indent}${routeConnector} ${verb} ${paddedPath}  ${m.name}()`);
    }

    // Recurse into child controllers
    for (let k = 0; k < children.length; k++) {
      itemIdx++;
      const isLastItem = itemIdx >= totalItems;
      renderSubtree(lines, children[k].name, controllers, indent, isLastItem);
    }
  } else {
    // No routes, just recurse into children
    const children = findChildControllers(info, controllers);
    for (let k = 0; k < children.length; k++) {
      renderSubtree(lines, children[k].name, controllers, indent, k === children.length - 1);
    }
  }
}

function findParentController(
  childName: string,
  controllers: Map<string, ControllerInfo>,
): ControllerInfo | null {
  for (const [, info] of controllers) {
    if (info.childControllers.includes(childName)) return info;
  }
  return null;
}

function findChildControllers(
  info: ControllerInfo,
  _controllers: Map<string, ControllerInfo>,
): Array<{ name: string }> {
  return info.childControllers.map((name) => ({ name }));
}

function buildDecoratorIndex(lines: string[], controllers: Map<string, ControllerInfo>): void {
  const seen = new Set<string>();

  const add = (decorator: string, controller: string, purpose: string) => {
    const key = `${decorator}|${controller}`;
    if (seen.has(key)) return;
    seen.add(key);
    lines.push(`| \`${decorator}\` | ${controller} | ${purpose} |`);
  };

  for (const [className, info] of controllers) {
    // Class-level decorators
    if (info.classMeta.path) add('@Path', className, 'Set base path');
    if (info.classMeta.tag) add('@Tag', className, 'Tag all routes');
    if (info.classMeta.name) add('@Name', className, 'Set route name prefix');
    if (info.classMeta.middleware && info.classMeta.middleware.length > 0) {
      add('@Middleware', className, 'Register middleware');
    }
    if (info.classMeta.flags && info.classMeta.flags.length > 0) {
      add('@Flag', className, 'Attach boolean flag');
    }
    if (info.classMeta.states) {
      for (const key of Object.keys(info.classMeta.states)) {
        if (key === 'exedra:validation') add('@Validation', className, 'Attach validation rules');
        else if (key === 'exedra:transformer') add('@Transformer', className, 'Shape response');
        else add('@State', className, 'Attach key/value state');
      }
    }
    if (info.classMeta.serieses && Object.keys(info.classMeta.serieses).length > 0) {
      add('@Series', className, 'Attach named array');
    }

    // Method-level decorators
    for (const m of info.methods) {
      if (m.httpVerb)
        add(
          `@${m.httpVerb.charAt(0) + m.httpVerb.slice(1).toLowerCase()}`,
          className,
          'Register route',
        );
      if (m.methodMeta.asFailRoute) add('@FailRoute', className, 'Catch-all route');
      if (m.methodMeta.name) add('@Name (method)', className, 'Set route name');
      if (m.routePath) add('@Path (method)', className, 'Set route path');
      if (m.methodMeta.states) {
        for (const key of Object.keys(m.methodMeta.states)) {
          if (key === 'exedra:validation') add('@Validation', className, 'Attach validation rules');
          else if (key === 'exedra:transformer') add('@Transformer', className, 'Shape response');
          else add('@State (method)', className, 'Attach state');
        }
      }
      if (m.methodMeta.flags) {
        add('@Flag (method)', className, 'Attach flag');
      }
      if (m.methodMeta.serieses) {
        add('@Series (method)', className, 'Attach series');
      }

      // Param decorators
      for (const binding of Object.values(m.paramBindings)) {
        const name = binding.type.charAt(0).toUpperCase() + binding.type.slice(1);
        add(`@${name}`, className, `Inject ${binding.type}`);
      }
    }
  }
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main() {
  const app = express();
  const rootGroup = createExedra(app, {
    controller: RootController,
    namedParamAutoInject: true,
    useFlatRouting: true,
  });

  const routes = rootGroup.listRoutes();
  const controllers = collectControllerInfo(rootGroup);

  const markdown = generateMarkdown(routes, controllers);
  fs.writeFileSync(OUTPUT_FILE, markdown, 'utf-8');
  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`  - ${routes.length} routes`);
  console.log(`  - ${controllers.size} controllers`);
}

main();
